# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  test:
    docker: 
      - image: 'cimg/node:18.0-browsers'
    steps:
      - checkout
      - run:
          name: NPM install
          command: cd web && npm install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Run unit tests
          command: cd web && npm run test -- --no-watch --browsers=Chrome
      - store_test_results:
          path: ./web/junit

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  application_explorer_web:
    jobs:
      - test


