# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  test_and_save:
    docker: 
      - image: 'cimg/node:18.0-browsers'
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
          working_directory: web
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Run unit tests
          command: npm run test -- --no-watch --browsers=Chrome
          working_directory: web
      - store_test_results:
          path: ./web/junit
      - save_cache:
          key: web-cache
          paths:
            - ./web

  build_server:
    docker:
      - image: 'cimg/node:18.0'
    working_directory: ~/project/web
    steps:
      - restore_cache:
          keys:
            - web-cache
      - run:
          name: Build server
          command: npx ng run angular:server

  build_browser:
    docker:
      - image: 'cimg/node:18.0'
    working_directory: ~/project/web
    steps:
      - restore_cache:
          keys:
          - web-cache
      - run:
          name: Build client
          command: npx ng build




# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  application_explorer_web:
    jobs:
      - test_and_save
      - build_server:
          requires:
            - test_and_save
      - build_browser:
          requires:
            - test_and_save


